"""new-rev

Revision ID: b54bbc39a9a8
Revises: 447f8bad1984
Create Date: 2024-11-14 11:13:42.839573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54bbc39a9a8'
down_revision: Union[str, None] = '447f8bad1984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('time', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'time')
    # ### end Alembic commands ###
